# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogGenericArtifacts@1
  inputs:
    command: 'Upload'
    connection: 'Test Natan'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
              "files": [
               {
                 "pattern": "cpp-example/*",
                 "target": "MyArtifact/",
                 "flat": "false"
               }
             ]
           }
    replaceSpecVars: true
    specVars: 'version=1.0'
    failNoOp: true








