# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: JFrogDotnetCore@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'Cloud Instance'
    targetResolveRepo: 'noffarl-azurepl-nuget'
    rootPath: 'dotnet-examples/single-example/*.csproj'