# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JfrogCliV2@1
  inputs:
    jfrogPlatformConnection: 'Cloud Instance JF'
    command: 'jf nuget restore --build-name="nuget-build-test" --build-number="1" noffarl-azurepl-nuget /dotnet-examples/single-example/'