# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogDotnetCore@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'Cloud Instance'
    targetResolveRepo: 'noffarl-azurepl-nuget'
    rootPath: 'dotnet-examples/single-example/**/*.csproj'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: JFrogCollectIssues@1
  inputs:
    artifactoryConnection: 'Cloud Instance'
    configSource: 'taskConfiguration'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'Cloud Instance'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'





